spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/billingdb
    username: billing_prod
    password: prodpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect 