spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/billingdb_dev
    username: billing_dev
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 