spring:
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/inferencedb
    username: inference_prod
    password: prodpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect 