spring:
  mail:
    host: smtp.example.com
    port: 587
    username: user
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 