spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/aibackend
  application:
    name: ai-baas-service
  cloud:
    config:
      uri: http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true 