server:
  port: 9008
spring:
  application:
    name: audit-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/auditdb
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true
    config:
      uri: http://localhost:8888
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*" 