server:
  port: 9006
spring:
  application:
    name: billing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/billingdb
    username: billing
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: true
    config:
      uri: http://localhost:8888
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*" 